### ISSUE TITLE
FALTA Especificaciones

### ISSUE THREAD

**Issue by garrongarron** [TODO-Game-Dev/random-todo#1]
**Aprovecho para hacer mi primer ISSUE en GITHUB y practicar mas con el desarrollo colavorativo.**

Solo quiero mencionar que quise colaborar con algo pero usando blender, 

- y me encontre con que en ninguna parte del repositorio se menciona que tipo de herramienta/tecnologia se usa o podria usar en el proyecto.

SALUDOS.

**Comment by rhomita** [comment]
Es un proyecto creado en Unity, por ende lo vas a necesitar para abrirlo. Por otro lado, vas a poder agregar arte (por ejemplo modelos de blender) sin necesidad de abrir el proyecto.
